version: "3"

services:
  web:
    build: .
    command: ./bin/rails server -e development -b 0.0.0.0 -p 80
    volumes:
      - .:/app
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      SECRET_KEY_BASE: secret

  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
