# The docker-compose.yml file is __only__ used for local development.
# This means that changes to this file will not affect cloud deployments in any way.
# Read more at https://docs.divio.com/reference/docker-docker-compose/
services:
  web:
    build: .
    # The following command is used to start the local development server.
    # Removing this line will mimic the deployment behaviour on Divio Cloud.
    command: ./bin/rails server -e development -b 0.0.0.0 -p 80
    volumes:
      - .:/rails
      - "./data:/data:rw"
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      SECRET_KEY_BASE: secret

  db:
    image: postgres:16-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
